version: '3.8'
services:
  db:
    image: postgres:15
    container_name: avloniy_db_container
    environment:
      POSTGRES_DB: avloniy_museum_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/avloniy_museum_db
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update